$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

function New-DevelopmentSecret {
    $bytes = New-Object byte[] 32
    $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    } finally {
        $generator.Dispose()
    }
    return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Read-DevelopmentVariable([string]$name) {
    if (-not (Test-Path -LiteralPath ".dev.vars")) {
        return ""
    }
    $prefix = "$name="
    $line = Get-Content -LiteralPath ".dev.vars" |
        Where-Object { $_.StartsWith($prefix) } |
        Select-Object -Last 1
    if (-not $line) {
        return ""
    }
    return $line.Substring($prefix.Length).Trim()
}

if (-not (Test-Path -LiteralPath ".dev.vars")) {
    $pepper = New-DevelopmentSecret
    $adminSecret = New-DevelopmentSecret
    @(
        "# Generated by scripts/start_account_debug.ps1. Do not commit this file."
        "ACCOUNT_HASH_PEPPER=$pepper"
        "LOCAL_ADMIN_SECRET=$adminSecret"
    ) | Set-Content -LiteralPath ".dev.vars" -Encoding utf8
    Write-Host "Created local-only account secrets in .dev.vars."
} else {
    $adminSecret = Read-DevelopmentVariable "LOCAL_ADMIN_SECRET"
    $pepper = Read-DevelopmentVariable "ACCOUNT_HASH_PEPPER"
    if (-not $pepper -or $pepper.Length -lt 32) {
        throw ".dev.vars must contain ACCOUNT_HASH_PEPPER with at least 32 characters."
    }
    if (-not $adminSecret) {
        throw ".dev.vars must contain LOCAL_ADMIN_SECRET."
    }
}

Write-Host ""
Write-Host "Applying local account database migrations..."
npx --yes wrangler d1 migrations apply writemelo-beta --local
if ($LASTEXITCODE -ne 0) {
    throw "Local D1 migration failed."
}

Write-Host ""
Write-Host "Account page: http://127.0.0.1:8787/support.html"
Write-Host "Admin page:   http://127.0.0.1:8787/support-admin.html"
Write-Host "Admin secret: $adminSecret"
Write-Host ""
Write-Host "Local login codes are shown directly on the account page."
Write-Host "Use Ctrl+C to stop the Worker."
npx --yes wrangler dev --ip 127.0.0.1 --port 8787
